# validate.yml
# Validates that AudibleApi will build on a pull request or push to master.
---
name: validate

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/build.yml
    with:
      project_file: ./AudibleApi/AudibleApi.csproj
      nuspec_file: ./AudibleApi.nuspec
